// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlschema

type RuntimeInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Labels      Labels  `json:"labels,omitempty"`
}
