// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	apperrors "github.com/kyma-project/compass-manager/internal/apperrors"

	gqlschema "github.com/kyma-project/compass-manager/pkg/gqlschema"

	graphql "github.com/kyma-incubator/compass/components/director/pkg/graphql"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CreateRuntime provides a mock function with given fields: config, tenant
func (_m *Client) CreateRuntime(config *gqlschema.RuntimeInput, tenant string) (string, apperrors.AppError) {
	ret := _m.Called(config, tenant)

	var r0 string
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(*gqlschema.RuntimeInput, string) (string, apperrors.AppError)); ok {
		return rf(config, tenant)
	}
	if rf, ok := ret.Get(0).(func(*gqlschema.RuntimeInput, string) string); ok {
		r0 = rf(config, tenant)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gqlschema.RuntimeInput, string) apperrors.AppError); ok {
		r1 = rf(config, tenant)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetConnectionToken provides a mock function with given fields: id, tenant
func (_m *Client) GetConnectionToken(id string, tenant string) (graphql.OneTimeTokenForRuntimeExt, apperrors.AppError) {
	ret := _m.Called(id, tenant)

	var r0 graphql.OneTimeTokenForRuntimeExt
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string) (graphql.OneTimeTokenForRuntimeExt, apperrors.AppError)); ok {
		return rf(id, tenant)
	}
	if rf, ok := ret.Get(0).(func(string, string) graphql.OneTimeTokenForRuntimeExt); ok {
		r0 = rf(id, tenant)
	} else {
		r0 = ret.Get(0).(graphql.OneTimeTokenForRuntimeExt)
	}

	if rf, ok := ret.Get(1).(func(string, string) apperrors.AppError); ok {
		r1 = rf(id, tenant)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

// GetRuntime provides a mock function with given fields: id, tenant
func (_m *Client) GetRuntime(id string, tenant string) (graphql.RuntimeExt, apperrors.AppError) {
	ret := _m.Called(id, tenant)

	var r0 graphql.RuntimeExt
	var r1 apperrors.AppError
	if rf, ok := ret.Get(0).(func(string, string) (graphql.RuntimeExt, apperrors.AppError)); ok {
		return rf(id, tenant)
	}
	if rf, ok := ret.Get(0).(func(string, string) graphql.RuntimeExt); ok {
		r0 = rf(id, tenant)
	} else {
		r0 = ret.Get(0).(graphql.RuntimeExt)
	}

	if rf, ok := ret.Get(1).(func(string, string) apperrors.AppError); ok {
		r1 = rf(id, tenant)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(apperrors.AppError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
