name: documentation
run-name: ${{github.event.pull_request.title}}
on: [ pull_request ]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@0524e79d8d7d1606112722dd7a3b5f5ce367de3e
        with:
          use-quiet-mode: 'yes'  
          use-verbose-mode: 'yes'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
          check-modified-files-only: 'yes'
          base-branch: '${{ github.base_ref }}'
