name: KIM Release

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes

jobs:
  run-release-tests:
    permissions:
      contents: read
    uses: ./.github/workflows/tests.yaml

  build-release-images:
    permissions:
      id-token: write # This is required for requesting the JWT token
      contents: read
    needs: run-release-tests
    if: needs.run-release-tests.result == 'success'
    uses: ./.github/workflows/build-image.yaml

  generate-release:
    needs: run-release-tests
    if: needs.run-release-tests.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases and uploading assets
    steps:
      - name: Create Release and Generate Notes
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-release-report:
    needs: generate-release
    if: needs.generate-release.result == 'success'
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/upload-release-report.yaml
    with:
      release_version: ${{ github.ref_name }}
    secrets:
      RELEASE_LOG_UPLOADER_SA: ${{ secrets.RELEASE_LOG_UPLOADER_SA }}

